#!/bin/bash

# Commands to manage dotfiles

set -o errexit -o nounset

help=$(cat <<'USAGE'
Usage: dotfiles command

Available commands are:
  apply  Apply salt states
  build  Build a Gentoo VM image
  clean  Remove generated build files
  help   Display this help and exit
USAGE
)

if [ $# -eq 0 ]; then
   echo "$help"
   exit 1
fi

# Location of Packer output including files needed during the build
export BUILD=${BUILD:-build}

# Environment vars from .env file
source_env() {
   if [ -f .env ]; then
      set -o allexport
      source .env
      set +o allexport
   fi
}

# Gentoo autobuilds (minimal install ISO and Stage 3 tarball)
source_autobuild_vars() {
   source gentoo/gentoo-autobuild-vars

   autobuild_vars="${BUILD}/autobuild-variables.pkrvars.hcl"
   cat > "$autobuild_vars" <<-EOF
	gentoo_keyring = "${GENTOO_KEYRING}"
	gentoo_mirrors = "${GENTOO_MIRRORS}"
	gentoo_release_mirror = "${RELEASE_MIRROR}"
	gentoo_rsync_mirror = "${RSYNC_MIRROR}"
	iso_checksum = "${ISO_CHECKSUM}"
	iso_url = "${ISO_URL}"
	stage3 = "${STAGE3}"
	EOF
}

# Auto-detect virtual machine vars
source_vm_vars() {
   # When Packer is invoked it sometimes calls out to checkpoint.hashicorp.com to
   # look for new versions of Packer. Disable this for security and privacy
   # reasons.
   export CHECKPOINT_DISABLE=1

   # Location of the Packer cache
   export PACKER_CACHE_DIR="${BUILD}/packer_cache"

   # Enable Packer log
   export PACKER_LOG=1

   source gentoo/gentoo-vm-vars

   vm_vars="${BUILD}/vm-variables.pkrvars.hcl"
   cat > "$vm_vars" <<-EOF
	cpuflags = "${CPU_FLAGS}"
	cpus = ${CPUS}
	memory = ${MEMORY}
	EOF
}

apply() {
   salt/salt-apply "$@"
}

build_gentoo_iso() {
   local only=${1:-false}
   if [ ! -e "${BUILD}/gentoo-iso" ]; then
      source_env
      source_autobuild_vars
      source_vm_vars
      export PACKER_LOG_PATH="${BUILD}/gentoo-iso.log"
      packer build \
             -var-file="$autobuild_vars" \
             -var-file="$vm_vars" \
             -var build="${BUILD}" \
             gentoo/gentoo.pkr.hcl
   elif $only; then
      (>&2 echo 'Nothing to be done for gentoo-iso!')
      exit 1
   fi
}

build_gentoo_salt() {
   build_gentoo_iso

   if [ ! -e "${BUILD}/gentoo-salt" ]; then
      source_env
      source_vm_vars
      export PACKER_LOG_PATH="${BUILD}/gentoo-salt.log"
      packer build \
             -var-file="$vm_vars" \
             -var build="${BUILD}" \
             salt/salt.pkr.hcl
   else
      (>&2 echo 'Nothing to be done for gentoo-salt!')
      exit 1
   fi
}

build() {
   local help=$(cat <<-USAGE
	Usage: dotfiles build [command]

	Builds a Gentoo VM using Packer, the default command is 'salt' if not specified.

	Available commands are:
	  iso   Build base Gentoo VM
	  salt  Build base and provision with salt
	  help  Display this help and exit
	USAGE
   )

   if [ $# -eq  0 ]; then
      build_gentoo_salt
      exit 0
   fi

   local only=true
   case "$1" in
      iso) shift; build_gentoo_iso $only ;;
      salt) shift; build_gentoo_salt ;;
      help) shift; echo "$help"; exit 0 ;;
      *) shift; echo "$help"; exit 1 ;;
   esac
}

# Remove all build output, including any downloaded Gentoo autobuilds,
# verification keys, caches, and VMs.
clean_all() {
   rm -rf "$BUILD"
}

# Remove VM build output. Accepts an optional parameter for the build type to
# remove, otherwise all VM builds are removed.
clean_build() {
   if [ $# -eq 0 ]; then
      clean_build 'iso'
      clean_build 'salt'
   else
      local type="${1}"
      rm -rf "${BUILD}/gentoo-${type}"{,.log}
   fi
}

# Call on the appropriate clean command
clean() {
   local help=$(cat <<-USAGE
	Usage: dotfiles clean [command]

	Remove build output, the default command is 'all' if not specified.

	Available commands are:
	  all           Remove all build output
	  build         Remove 'iso' and 'salt' builds
	  build <type>  Remove only 'iso' or 'salt' builds
	  help          Display this help and exit
	USAGE
   )

   # Default to the 'all' clean command
   if [ $# -eq  0 ]; then
      clean_all
      exit 0
   fi

   case "$1" in
      all) shift; clean_all ;;
      build) shift; clean_build "$@" ;;
      help) shift; echo "$help"; exit 0 ;;
      *) shift; echo "$help"; exit 1 ;;
   esac
}

# Run relative to the source directory
cd "${BASH_SOURCE%/*}"

case "$1" in
   apply) shift; apply "$@" ;;
   clean) shift; clean "$@" ;;
   build) shift; build "$@" ;;
   help) shift; echo "$help"; exit 0 ;;
   *) shift; echo "$help"; exit 1 ;;
esac
