#!/bin/bash -uex

# Prepare the disks by adding paritions for system files, boot/kernel files,
# and swap.
#
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Disks

sgdisk \
  --new 1:0:+128M --typecode 1:EF00 --change-name 1:"linux-boot" \
  --new 2:0:0     --typecode 2:8E00 --change-name 2:"linux-lvm" \
  --print /dev/sda

# Using LVM to allow for more flexibility and control over partitions
pvcreate /dev/sda2
vgcreate "$ROOT_VOLUME_GROUP" /dev/sda2
lvcreate --name swap --size 1G "$ROOT_VOLUME_GROUP"
lvcreate --name root --extents 50%VG "$ROOT_VOLUME_GROUP"

# Using FAT because UEFI needs it
mkfs.vfat "$BOOT_DEVICE"

# Using Btrfs for many reasons, but a major one is snapshots for recovery of
# accidentally deleted files.
mkfs.btrfs "$ROOT_DEVICE"

mkswap "$SWAP_DEVICE"
swapon "$SWAP_DEVICE"
