#!/bin/bash -uex

sgdisk \
  --new 1:0:+128M --typecode 1:EF00 --change-name 1:"linux-boot" \
  --new 2:0:0     --typecode 2:8E00 --change-name 2:"linux-lvm" \
  --print /dev/sda

pvcreate /dev/sda2
vgcreate "$ROOT_VOLUME_GROUP" /dev/sda2
lvcreate --name swap --size 1G "$ROOT_VOLUME_GROUP"
lvcreate --name root --extents 50%VG "$ROOT_VOLUME_GROUP"

mkfs.vfat "$BOOT_DEVICE"
mkfs.btrfs "$ROOT_DEVICE"

mkswap "$SWAP_DEVICE"
swapon "$SWAP_DEVICE"
