#!/bin/bash -uex

# Set the time allowing a big adjustment and quit. The base system files should
# be extracted with accurate time stamps.
ntpd --quit --panicgate

tarball="stage3-amd64-${STAGE3}.tar.xz"
stage3_url="${MIRROR}/releases/${ARCH}/autobuilds/${STAGE3}/${tarball}"

tarball_temp="$(mktemp -d)" && trap "rm -r \"$tarball_temp\"" EXIT
wget --directory-prefix="$tarball_temp" --quiet "$stage3_url"{,.DIGESTS.asc}

gpgv --quiet --homedir "${AUTOBUILD_KEYRING}" "${tarball_temp}/${tarball}.DIGESTS.asc"
cd "$tarball_temp" || exit
awk '/# SHA512 HASH/{getline; print}' "${tarball}.DIGESTS.asc" \
   | grep "${tarball}$" \
   | sha512sum --check --status -
cd -

mkdir --parents /mnt/btrfs
mount --read-write --options defaults,noatime "$ROOT_DEVICE" /mnt/btrfs
btrfs subvolume create /mnt/btrfs/root

mkdir --parents /mnt/gentoo
mount --read-write --options defaults,noatime,subvol=root "$ROOT_DEVICE" /mnt/gentoo

tar --extract \
    --xz \
    --preserve-permissions \
    --xattrs-include='*.*' \
    --numeric-owner \
    --file "${tarball_temp}/${tarball}" \
    --directory /mnt/gentoo
