#!/bin/bash

# Install stage 3 tarball which contains an almost-complete and
# almost-functional Gentoo system.
#
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Stage

set -o errexit -o nounset -o xtrace

# Set the time allowing a big adjustment and quit. The base system files should
# be extracted with accurate time stamps.
ntpd --quit --panicgate

# Choose multilib (32-bit and 64-bit) stage 3 for now because 32-bit is still
# needed for some applications.
stage="stage3-amd64-openrc-${GENTOO_STAGE}.tar.xz"
stage_url="${RELEASE_MIRROR}/releases/amd64/autobuilds/${GENTOO_STAGE}/${stage}"

# Download stage file making sure to remove it later
stage_dir="$(mktemp -d)" && trap "rm -r \"$stage_dir\"" EXIT
wget --directory-prefix="$stage_dir" --quiet "$stage_url"{.DIGESTS.asc,}

# Verify and validate stage file
gpgv --quiet --keyring "$GENTOO_KEYRING" "${stage_dir}/${stage}.DIGESTS.asc"
(
cd "$stage_dir"
awk '/# SHA512 HASH/{getline; print}' "${stage}.DIGESTS.asc" \
   | grep "${stage}$" \
   | sha512sum --check --status -
)

# Create a subvolume for the base system
mkdir --parents "$BTRFS_MOUNT_POINT"
mount --read-write --options defaults,noatime "$ROOT_DEVICE" "$BTRFS_MOUNT_POINT"
btrfs subvolume create "${BTRFS_MOUNT_POINT}/root"

mkdir --parents "$GENTOO_MOUNT_POINT"
mount --read-write --options defaults,noatime,subvol=root "$ROOT_DEVICE" "$GENTOO_MOUNT_POINT"

# Unpack stage tarball
tar --extract \
    --xz \
    --preserve-permissions \
    --xattrs-include='*.*' \
    --numeric-owner \
    --file "${stage_dir}/${stage}" \
    --directory "$GENTOO_MOUNT_POINT"
