#!/bin/bash -uex

# Make certain filesystems available in the new environment
mount --read-write "${BOOT_DEVICE}" /mnt/gentoo/boot
mount --types proc proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
