#!/bin/bash

set -o errexit -o nounset -o xtrace

# Make certain filesystems available in the new environment
mount --read-write "${BOOT_DEVICE}" "${GENTOO_MOUNT_POINT}/boot"
mount --types proc proc "${GENTOO_MOUNT_POINT}/proc"
mount --rbind /sys "${GENTOO_MOUNT_POINT}/sys"
mount --make-rslave "${GENTOO_MOUNT_POINT}/sys"
mount --rbind /dev "${GENTOO_MOUNT_POINT}/dev"
mount --make-rslave "${GENTOO_MOUNT_POINT}/dev"
