#!/bin/bash

set -o errexit -o nounset -o xtrace

# Configure Portage

btrfs subvolume create "${BTRFS_MOUNT_POINT}/repos"
btrfs subvolume create "${BTRFS_MOUNT_POINT}/distfiles"

mount --read-write --options defaults,noatime,subvol=repos "$ROOT_DEVICE" "${GENTOO_MOUNT_POINT}/var/db/repos"
mount --read-write --options defaults,noatime,subvol=distfiles "$ROOT_DEVICE" "${GENTOO_MOUNT_POINT}/var/cache/distfiles"

# Use the latest daily snapshot
snapshot=portage-latest.tar.xz
snapshot_url="${RELEASE_MIRROR}/snapshots/${snapshot}"

# Download a snapshot of the main ebuild repository
snapshot_dir="$(mktemp -d)" && trap "rm -r \"$snapshot_dir\"" EXIT
wget --directory-prefix="$snapshot_dir" --quiet "$snapshot_url"{.gpgsig,.md5sum,}

# Verify and validate snapshot
gpgv --quiet --keyring "$GENTOO_KEYRING" "${snapshot_dir}/${snapshot}"{.gpgsig,}
(
cd "$snapshot_dir"
md5sum --check --status "${snapshot}.md5sum"
)

# Unpack the snapshot
mkdir "${GENTOO_MOUNT_POINT}/var/db/repos/gentoo"
tar --extract \
    --xz \
    --file "${snapshot_dir}/${snapshot}" \
    --strip-components=1 \
    --directory "${GENTOO_MOUNT_POINT}/var/db/repos/gentoo"

cp --recursive "${SOURCE:-.}/portage" "${GENTOO_MOUNT_POINT}/tmp/"

chroot "$GENTOO_MOUNT_POINT" /bin/bash <<'EOF'
set -o errexit -o nounset -o xtrace

mkdir --parents /etc/portage/repos.conf
envsubst '$CPUS $CPU_FLAGS_X86 $GENTOO_MIRRORS' < /tmp/portage/make.conf > /etc/portage/make.conf
envsubst '$RSYNC_MIRROR' < /tmp/portage/gentoo.conf > /etc/portage/repos.conf/gentoo.conf
rm --recursive /tmp/portage

# Configure locales
cat >> /etc/locale.gen <<'DATA'
en_US ISO-8859-1
en_US.UTF-8 UTF-8
DATA

# Generate locales
locale-gen

# Set the system-wide locale
eselect locale set en_US.utf8

# Suppress notification about news items
eselect news read --quiet all
EOF
