#!/bin/bash -uex

# Configure Portage

REPOSDIR=/var/db/repos
export PORTDIR=${REPOSDIR}/gentoo
export DISTDIR=/var/cache/distfiles

mkdir --parents /mnt/gentoo{$REPOSDIR,$DISTDIR}
btrfs subvolume create /mnt/btrfs/repos
btrfs subvolume create /mnt/btrfs/distfiles

mount --read-write --options defaults,noatime,subvol=repos "$ROOT_DEVICE" /mnt/gentoo${REPOSDIR}
mount --read-write --options defaults,noatime,subvol=distfiles "$ROOT_DEVICE" /mnt/gentoo${DISTDIR}

# Use the latest daily snapshot
tarball='portage-latest.tar.xz'
snapshots_url="${RELEASE_MIRROR}/snapshots/${tarball}"

# Download a snapshot of the main ebuild repository
tarball_temp="$(mktemp -d)" && trap "rm -r \"$tarball_temp\"" EXIT
wget --directory-prefix="$tarball_temp" --quiet "$snapshots_url"{.gpgsig,.md5sum,}

# Verify and validate snapshot
gpgv --quiet --keyring "$GENTOO_KEYRING" "${tarball_temp}/${tarball}"{.gpgsig,}
cd "$tarball_temp" || exit
md5sum --check --status "${tarball}.md5sum"
cd -

# Unpack the snapshot
mkdir /mnt/gentoo${PORTDIR}
tar --extract \
    --xz \
    --file "${tarball_temp}/${tarball}" \
    --strip-components=1 \
    --directory /mnt/gentoo${PORTDIR}

chown root:portage /mnt/gentoo${PORTDIR}
chown root:portage /mnt/gentoo${DISTDIR}

cp --recursive "${SOURCE}/portage" /mnt/gentoo/tmp/

if [ "$USE_VIRTUALBOX" = 'true' ]; then
   export VIDEO_CARDS='$VIDEO_CARDS vmware'
else
   export VIDEO_CARDS='$VIDEO_CARDS'
fi

chroot /mnt/gentoo /bin/bash -uex <<'EOF'
mkdir --parents /etc/portage/repos.conf
envsubst '$CPUS $CPU_FLAGS_X86 $DISTDIR $GENTOO_MIRRORS $PORTDIR $VIDEO_CARDS' < /tmp/portage/make.conf > /etc/portage/make.conf
envsubst '$PORTDIR $RSYNC_MIRROR' < /tmp/portage/gentoo.conf > /etc/portage/repos.conf/gentoo.conf
rm --recursive /tmp/portage
EOF

chroot /mnt/gentoo /bin/bash -uex <<EOF
ln --symbolic $PORTDIR /usr/portage

emerge --sync --quiet

# Suppress notification about news items
eselect news read --quiet all

eselect profile set default/linux/amd64/17.1

emerge --quiet --update --deep --newuse @system
EOF
