#!/bin/bash

set -o errexit -o nounset -o xtrace

# Configure Portage

btrfs subvolume create /mnt/btrfs/repos
btrfs subvolume create /mnt/btrfs/distfiles

mount --read-write --options defaults,noatime,subvol=repos "$ROOT_DEVICE" /mnt/gentoo/var/db/repos
mount --read-write --options defaults,noatime,subvol=distfiles "$ROOT_DEVICE" /mnt/gentoo/var/cache/distfiles

# Use the latest daily snapshot
tarball=portage-latest.tar.xz
snapshots_url="${RELEASE_MIRROR}/snapshots/${tarball}"

# Download a snapshot of the main ebuild repository
tarball_temp="$(mktemp -d)" && trap "rm -r \"$tarball_temp\"" EXIT
wget --directory-prefix="$tarball_temp" --quiet "$snapshots_url"{.gpgsig,.md5sum,}

# Verify and validate snapshot
gpgv --quiet --keyring "$GENTOO_KEYRING" "${tarball_temp}/${tarball}"{.gpgsig,}
(
cd "$tarball_temp"
md5sum --check --status "${tarball}.md5sum"
)

# Unpack the snapshot
mkdir /mnt/gentoo/var/db/repos/gentoo
tar --extract \
    --xz \
    --file "${tarball_temp}/${tarball}" \
    --strip-components=1 \
    --directory /mnt/gentoo/var/db/repos/gentoo

cp --recursive "${SOURCE:-.}/portage" /mnt/gentoo/tmp/

chroot /mnt/gentoo /bin/bash <<'EOF'
set -o errexit -o nounset -o xtrace

mkdir --parents /etc/portage/repos.conf
envsubst '$CPUS $CPU_FLAGS_X86 $GENTOO_MIRRORS' < /tmp/portage/make.conf > /etc/portage/make.conf
envsubst '$RSYNC_MIRROR' < /tmp/portage/gentoo.conf > /etc/portage/repos.conf/gentoo.conf
rm --recursive /tmp/portage

# Configure locales
cat >> /etc/locale.gen <<'DATA'
en_US ISO-8859-1
en_US.UTF-8 UTF-8
DATA

# Generate locales
locale-gen

# Set the system-wide locale
eselect locale set en_US.utf8

# Suppress notification about news items
eselect news read --quiet all
EOF
