#!/bin/bash

set -o errexit -o nounset -o xtrace

mkdir --parents "${GENTOO_MOUNT_POINT}/home/evan"
mkdir --parents "${GENTOO_MOUNT_POINT}/snapshots/.evan"
mkdir --parents "${GENTOO_MOUNT_POINT}/snapshots/.root"

btrfs subvolume create "${BTRFS_MOUNT_POINT}/evan"

BOOT_UUID="$(blkid -s UUID -o value "$BOOT_DEVICE")"
ROOT_UUID="$(blkid -s UUID -o value "$ROOT_DEVICE")"
SWAP_UUID="$(blkid -s UUID -o value "$SWAP_DEVICE")"

chroot "$GENTOO_MOUNT_POINT" /bin/bash <<EOF
set -o errexit -o nounset -o xtrace

cat > /etc/fstab <<'DATA'
# <fs>              <mount>                 <type>   <opts>                              <dump/pass>
UUID=${ROOT_UUID}   /                       btrfs    defaults,noatime,subvol=root        0 0
UUID=${BOOT_UUID}   /boot                   vfat     noauto,noatime                      0 0
UUID=${ROOT_UUID}   /home/evan              btrfs    defaults,noatime,subvol=evan        0 0
UUID=${ROOT_UUID}   /snapshots/.evan        btrfs    defaults,noatime                    0 0
UUID=${ROOT_UUID}   /snapshots/.root        btrfs    defaults,noatime                    0 0
UUID=${ROOT_UUID}   /var/cache/distfiles    btrfs    defaults,noatime,subvol=distfiles   0 0
UUID=${ROOT_UUID}   /var/db/repos           btrfs    defaults,noatime,subvol=repos       0 0
UUID=${SWAP_UUID}   none                    swap     sw                                  0 0
DATA
EOF
