#!/bin/bash -uex

mkdir --parents /mnt/gentoo/home/evan
mkdir --parents /mnt/gentoo/snapshots/.{evan,root}

btrfs subvolume create /mnt/btrfs/evan
mount --read-write --options defaults,noatime,subvol=evan "$ROOT_DEVICE" /mnt/gentoo/home/evan
mount --read-write --options defaults,noatime "$ROOT_DEVICE" /mnt/gentoo/snapshots/.evan
mount --read-write --options defaults,noatime "$ROOT_DEVICE" /mnt/gentoo/snapshots/.root

BOOT_UUID="$(blkid -s UUID -o value "$BOOT_DEVICE")"
ROOT_UUID="$(blkid -s UUID -o value "$ROOT_DEVICE")"
SWAP_UUID="$(blkid -s UUID -o value "$SWAP_DEVICE")"

chroot /mnt/gentoo /bin/bash -uex <<EOF
cat > /etc/fstab <<'DATA'
# <fs>              <mount>                 <type>   <opts>                              <dump/pass>
UUID=${ROOT_UUID}   /                       btrfs    defaults,noatime,subvol=root        0 0
UUID=${BOOT_UUID}   /boot                   vfat     noauto,noatime                      0 0
UUID=${ROOT_UUID}   /home/evan              btrfs    defaults,noatime,subvol=evan        0 0
UUID=${ROOT_UUID}   /snapshots/.evan        btrfs    defaults,noatime                    0 0
UUID=${ROOT_UUID}   /snapshots/.root        btrfs    defaults,noatime                    0 0
UUID=${ROOT_UUID}   /var/cache/distfiles    btrfs    defaults,noatime,subvol=distfiles   0 0
UUID=${ROOT_UUID}   /var/db/repos           btrfs    defaults,noatime,subvol=repos       0 0
UUID=${SWAP_UUID}   none                    swap     sw                                  0 0
DATA
EOF
