#!/bin/bash

chroot "$GENTOO_MOUNT_POINT" /bin/bash <<'EOF'
set -o errexit -o xtrace

ln -s /etc/init.d/net.lo /etc/init.d/net.enp0s3
rc-update add net.enp0s3 default
emerge --quiet net-misc/dhcpcd
EOF
