#!/bin/bash -uex

chroot /mnt/gentoo /bin/bash -uex <<'EOF'
UID_GID=1337
groupadd -g $UID_GID evan
useradd --no-create-home --uid $UID_GID --gid $UID_GID --groups wheel --shell /bin/bash evan
chmod 750 /home/evan /snapshots/.evan
chown evan: /home/evan /snapshots/.evan

echo evan:correcthorsebatterystaple | chpasswd
echo root:correcthorsebatterystaple | chpasswd

eselect profile set default/linux/amd64/17.0/desktop

# configure ssh for second stage provisioning
sed --in-place 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sed --in-place 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
rc-update add sshd default
EOF
