#!/bin/bash

# Detect and optimize for system resources

set -o errexit -o nounset -o xtrace

# Use cpuid2cpuflags utility to query a listing of CPU flags supported by the
# system's processor. The flags are used by Portage to optimize package builds
# in /etc/portage/make.conf.
#
# https://wiki.gentoo.org/wiki/CPU_FLAGS_X86
CPU_FLAGS=${CPU_FLAGS:-$(command -v cpuid2cpuflags >/dev/null 2>&1 && cpuid2cpuflags || :)}
# Remove label added by cpuid2cpuflags
CPU_FLAGS="${CPU_FLAGS##*CPU_FLAGS_X86: }"

# The number of virtual CPUs for the virtual machine. Also used in make.conf
# MAKEOPTS to set the number of simultaneous jobs.
#
# https://wiki.gentoo.org/wiki/MAKEOPTS
CPUS=${CPUS:-$(nproc --all)}

# The amount of RAM, in MB, that the virtual machine should allocate for itself
# from the host. Compilation can take up a lot of memory and more as the make
# jobs increase (See CPUS above).
MEMORY=${MEMORY:-$(echo "($CPUS * 1024 * 1.5) / 1" | bc)} # 1.5 GiB per CPU is an estimate

# Export to be referenced later in the build
export CPU_FLAGS
export CPUS
export MEMORY
