#!/bin/bash

# Download and verify Gentoo Linux installation ISO
#
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Media

set -o errexit -o nounset -o xtrace

# Gentoo source and Portage tree mirrors, if empty automatically select a mirror
if [ -z "${GENTOO_MIRRORS:-}" ]; then
   GENTOO_MIRRORS=$(mirrorselect -R "${MIRRORSELECT_REGION:-North America}" \
                                 -c "${MIRRORSELECT_COUNTRY:-USA}" --http -o \
      | grep 'GENTOO_MIRRORS=' | tr -d '"' | sed 's/\/$//')
   GENTOO_MIRRORS="${GENTOO_MIRRORS#GENTOO_MIRRORS=}"
fi
GENTOO_MIRRORS=${GENTOO_MIRRORS:-http://distfiles.gentoo.org}
RELEASE_MIRROR=${RELEASE_MIRROR:-${GENTOO_MIRRORS%% *}}
RSYNC_MIRROR=${RSYNC_MIRROR:-rsync://rsync.gentoo.org/gentoo-portage}

# Get the path to the latest autobuild
DIST="${RELEASE_MIRROR}/releases/amd64/autobuilds"
ISO_PATH=$(wget -q -O- "${DIST}/latest-install-amd64-minimal.txt" | tail -n 1 | cut -f 1 -d ' ')
ISO="$(basename "$ISO_PATH")"
AUTOBUILD="$(dirname "$ISO_PATH")"
AUTOBUILD_DIR="${BUILD}/autobuilds/${AUTOBUILD}"

# Download the Gentoo Linux installation ISO
mkdir --parents "$AUTOBUILD_DIR"
wget --continue --directory-prefix "${AUTOBUILD_DIR}" "${DIST}/${ISO_PATH}"{,.CONTENTS.gz,.asc}

# Try to verify using Gentoo signing keys from
# app-crypt/openpgp-keys-gentoo-release, otherwise fetch from Gentoo's
# keyserver.
GENTOO_KEYS="${BUILD}/gentoo-keys"
GENTOO_KEYRING="${GENTOO_KEYS}/gentoo-release.asc"
(
umask 077

mkdir --parents "$GENTOO_KEYS"
if [ -f /usr/share/openpgp-keys/gentoo-release.asc ]; then
   gpg --quiet \
       --homedir "$GENTOO_KEYS" \
       --no-default-keyring \
       --keyring "$GENTOO_KEYRING" \
       --import /usr/share/openpgp-keys/gentoo-release.asc
else
   # Gentoo automated release and ebuild repository signing keys
   # https://www.gentoo.org/downloads/signatures/
   WEEKLY_RELEASE_SIGNING_KEY=13EBBDBEDE7A12775DFDB1BABB572E0E2D182910
   EBUILD_REPOSITORY_SIGNING_KEY=DCD05B71EAB94199527F44ACDB6B8C1F96D8BF6D

   gpg --quiet \
       --homedir "$GENTOO_KEYS" \
       --no-default-keyring \
       --keyring "$GENTOO_KEYRING" \
       --keyserver hkps://keys.gentoo.org \
       --recv-keys $WEEKLY_RELEASE_SIGNING_KEY $EBUILD_REPOSITORY_SIGNING_KEY
fi
)

# Verify ISO has been provided by the Gentoo Infrastructure team
gpgv --quiet --keyring "$GENTOO_KEYRING" "${AUTOBUILD_DIR}/${ISO}.asc" "${AUTOBUILD_DIR}/${ISO}"

# Export to be referenced later in the build
export GENTOO_KEYRING
export GENTOO_MIRRORS
export GENTOO_STAGE=$AUTOBUILD
export RELEASE_MIRROR
export RSYNC_MIRROR
export ISO_CHECKSUM=$(sha512sum "${AUTOBUILD_DIR}/${ISO}" | cut -f 1 -d ' ')
export ISO_URL="./${AUTOBUILD_DIR}/${ISO}"
