#!/bin/bash

set -uex

ARCH=amd64
MIRROR=${DIST_MIRROR:-http://distfiles.gentoo.org}
RSYNC_MIRROR=${RSYNC_MIRROR:-rsync://rsync.gentoo.org/gentoo-portage}

WEEKLY_RELEASE_SIGNING_KEY=0x13EBBDBEDE7A12775DFDB1BABB572E0E2D182910
EBUILD_REPOSITORY_SIGNING_KEY=0xDCD05B71EAB94199527F44ACDB6B8C1F96D8BF6D

DIST="${MIRROR}/releases/${ARCH}/autobuilds"
ISO_PATH=$(wget -q -O- "${DIST}/latest-install-${ARCH}-minimal.txt" | tail -n 1 | cut -f 1 -d ' ')
ISO="$(basename "$ISO_PATH")"
BUILD=build
AUTOBUILD="$(dirname "$ISO_PATH")"
AUTOBUILD_DIR="${BUILD}/autobuilds/${AUTOBUILD}"
AUTOBUILD_KEYRING="${BUILD}/autobuilds/keyring"

mkdir --parents "$AUTOBUILD_DIR"
wget --continue --directory-prefix "${AUTOBUILD_DIR}" "${DIST}/${ISO_PATH}"{,.CONTENTS,.DIGESTS.asc}

OLD_UMASK=$(umask)
umask 077
mkdir --parents "$AUTOBUILD_KEYRING"
gpg --quiet \
    --homedir "$AUTOBUILD_KEYRING" \
    --no-default-keyring \
    --keyring trustedkeys.gpg \
    --keyserver hkps.pool.sks-keyservers.net \
    --recv-keys ${WEEKLY_RELEASE_SIGNING_KEY} ${EBUILD_REPOSITORY_SIGNING_KEY}
gpgv --homedir "$AUTOBUILD_KEYRING" "${AUTOBUILD_DIR}/${ISO}.DIGESTS.asc"
umask "${OLD_UMASK}"

cd $AUTOBUILD_DIR
ISO_CHECKSUM="$(awk '/# SHA512 HASH/{getline; print}' ${ISO}.DIGESTS.asc)"
echo "$ISO_CHECKSUM" | sha512sum --check --status -
cd -
ISO_CHECKSUM=$(echo "$ISO_CHECKSUM" | head -n 1 | cut -f 1 -d ' ')
cat << EOF > ${BUILD}/autobuild-variables.json
{
  "arch": "${ARCH}",
  "iso_checksum": "${ISO_CHECKSUM}",
  "iso_url": "file://${AUTOBUILD_DIR}/${ISO}",
  "mirror": "${MIRROR}",
  "rsync_mirror": "${RSYNC_MIRROR}",
  "stage3": "${AUTOBUILD}"
}
EOF
