#!/bin/bash

set -uex

CPU_FLAGS=$(command -v cpuid2cpuflags >/dev/null 2>&1 && cpuid2cpuflags || true)
CPUS=$(nproc --all)
MEMORY=20480
VIDEO_MEMORY=128

BUILD=build
cat << EOF > ${BUILD}/vm-variables.json
{
  "cpuflags": "${CPU_FLAGS##*CPU_FLAGS_X86: }",
  "cpus": "${CPUS}",
  "memory": "${MEMORY}",
  "vram": "${VIDEO_MEMORY}"
}
EOF
