#!/bin/bash -uex

tarball="stage3-amd64-${STAGE3}.tar.xz"
stage3_url="${MIRROR}/releases/${ARCH}/autobuilds/${STAGE3}/${tarball}"

tarball_temp="$(mktemp -d)"
cd "$tarball_temp"
wget --quiet "$stage3_url" "${stage3_url}.DIGESTS.asc"
trap "rm -r \"$tarball_temp\"" EXIT

gpgv --quiet --homedir "${AUTOBUILD_KEYRING}" "${tarball}.DIGESTS.asc"
awk '/# SHA512 HASH/{getline; print}' "${tarball}.DIGESTS.asc" \
   | grep "${tarball}$" \
   | sha512sum --check --status -

mkdir --parents /mnt/gentoo
mount --read-write ${ROOT_DEVICE} /mnt/gentoo
tar --extract \
    --xz \
    --preserve-permissions \
    --xattrs-include='*.*' \
    --numeric-owner \
    --file "$tarball" \
    --directory /mnt/gentoo
