#!/bin/bash -uex

tarball="stage3-amd64-${STAGE3}.tar.xz"
[ $ARCH == "x86" ] && tarball="stage3-i686-${STAGE3}.tar.xz" || true

stage3_url="${MIRROR}/releases/${ARCH}/autobuilds/${STAGE3}/${tarball}"

tarball_temp="$(mktemp -d)"
cd "$tarball_temp"
wget --quiet "$stage3_url" "${stage3_url}.DIGESTS.asc"
trap "rm -r \"$tarball_temp\"" EXIT

gpg --quiet \
    --no-default-keyring \
    --keyring trustedkeys.gpg \
    --keyserver hkps.pool.sks-keyservers.net \
    --recv-keys 0x13EBBDBEDE7A12775DFDB1BABB572E0E2D182910
gpgv --quiet "${tarball}.DIGESTS.asc"
awk '/# SHA512 HASH/{getline; print}' "${tarball}.DIGESTS.asc" \
   | grep "${tarball}$" \
   | shasum --algorithm 512 --check --status -

mkdir --parents /mnt/gentoo
mount --read-write ${ROOT_DEVICE} /mnt/gentoo
tar --extract \
    --xz \
    --preserve-permissions \
    --xattrs-include='*.*' \
    --numeric-owner \
    --file "$tarball" \
    --directory /mnt/gentoo
