#!/bin/bash -uex

tarball='portage-latest.tar.xz'
snapshots_url="${MIRROR}/snapshots/${tarball}"

tarball_temp="$(mktemp -d)"
cd "$tarball_temp"
wget --quiet "$snapshots_url" "${snapshots_url}.gpgsig"
trap "rm -r \"$tarball_temp\"" EXIT

gpgv --quiet --homedir "${AUTOBUILD_KEYRING}" "${tarball}.gpgsig" "$tarball"

mkdir --parents /mnt/gentoo/usr/portage
tar --extract \
    --xz \
    --warning=no-timestamp \
    --numeric-owner \
    --file "$tarball" \
    --directory /mnt/gentoo/usr

chroot /mnt/gentoo /bin/bash -uex <<EOF
mkdir --parents /etc/portage/repos.conf
cp /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf
sed --in-place 's~rsync://rsync.gentoo.org/gentoo-portage~${RSYNC_MIRROR}~' /etc/portage/repos.conf/gentoo.conf
echo "MAKEOPTS=\"${MAKEOPTS}\"" >> /etc/portage/make.conf
EOF

chroot /mnt/gentoo /bin/bash -uex <<'EOF'
echo 'EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --buildpkg --getbinpkg"' >> /etc/portage/make.conf
# TODO replace with more permanent host or a self hosted solution (nfs?)
echo 'PORTAGE_BINHOST="http://10.0.2.2:8000/packages"' >> /etc/portage/make.conf

emerge --sync --quiet

# suppress notification about news items
eselect news read --quiet all

emerge --verbose --quiet --update --deep --newuse @system
EOF
