#!/bin/bash -uex

tarball='portage-latest.tar.xz'
snapshots_url="${MIRROR}/snapshots/${tarball}"

tarball_temp="$(mktemp -d)" && trap "rm -r \"$tarball_temp\"" EXIT
wget --directory-prefix="$tarball_temp" --quiet "$snapshots_url"{,.gpgsig}

gpgv --quiet --homedir "${AUTOBUILD_KEYRING}" "${tarball_temp}/${tarball}"{.gpgsig,}

mkdir --parents /mnt/gentoo/usr/portage
tar --extract \
    --xz \
    --warning=no-timestamp \
    --numeric-owner \
    --file "${tarball_temp}/${tarball}" \
    --directory /mnt/gentoo/usr

chroot /mnt/gentoo /bin/bash -uex <<EOF
mkdir --parents /etc/portage/repos.conf
cp /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf
sed --in-place 's~rsync://rsync.gentoo.org/gentoo-portage~${RSYNC_MIRROR}~' /etc/portage/repos.conf/gentoo.conf

echo "MAKEOPTS=\"${MAKEOPTS}\"" >> /etc/portage/make.conf

emerge --sync --quiet

# suppress notification about news items
eselect news read --quiet all

emerge --verbose --quiet --update --deep --newuse @system
EOF
