#!/bin/bash -uex

tarball='portage-latest.tar.xz'
snapshots_url="${MIRROR}/snapshots/${tarball}"

tarball_temp="$(mktemp -d)" && trap "rm -r \"$tarball_temp\"" EXIT
wget --directory-prefix="$tarball_temp" --quiet "$snapshots_url"{,.gpgsig}

gpgv --quiet --homedir "${AUTOBUILD_KEYRING}" "${tarball_temp}/${tarball}"{.gpgsig,}

export PORTDIR=/usr/portage
export DISTDIR=/usr/portage/distfiles
mkdir --parents /mnt/gentoo$PORTDIR
tar --extract \
    --xz \
    --warning=no-timestamp \
    --numeric-owner \
    --file "${tarball_temp}/${tarball}" \
    --directory /mnt/gentoo/usr

cp --recursive "${SOURCE}/portage" /mnt/gentoo/tmp/
chroot /mnt/gentoo /bin/bash -uex <<'EOF'
mkdir --parents /etc/portage/repos.conf
envsubst '$CPUS $PORTDIR $DISTDIR $CPU_FLAGS_X86' < /tmp/portage/make.conf > /etc/portage/make.conf
envsubst '$PORTDIR $RSYNC_MIRROR' < /tmp/portage/repos.conf/gentoo.conf > /etc/portage/repos.conf/gentoo.conf
rm --recursive /tmp/portage
EOF

chroot /mnt/gentoo /bin/bash -uex <<EOF
emerge --sync --quiet

# suppress notification about news items
eselect news read --quiet all

emerge --verbose --quiet --update --deep --newuse @system
EOF
