#!/bin/bash

set -o errexit -o nounset -o xtrace

# Salt USE flags are managed here as well as in salt/init.sls.
# It is probably best to keep them in sync.
mkdir --parents /etc/portage/package.use/{app-admin,net-libs}
echo 'app-admin/salt gnupg portage vim-syntax' > /etc/portage/package.use/app-admin/salt
# pyzmq seems to need zeromq drafts enabled?
# https://bugs.gentoo.org/703252
# https://bugs.gentoo.org/648088
echo '>=net-libs/zeromq-4.3.2 drafts' > /etc/portage/package.use/net-libs/zeromq

emerge --quiet app-admin/salt
rc-update add salt-minion

cp /tmp/minion /etc/salt/minion
echo $MINION_ID > /etc/salt/minion_id

OLD_UMASK=$(umask)
umask 077
mkdir --parents /etc/salt/gpgkeys
gpg --homedir /etc/salt/gpgkeys --import /tmp/pillar.asc
umask "${OLD_UMASK}"

mkdir --parents /srv/salt /srv/pillar
cp -r /tmp/pillar/* /srv/pillar
cp -r /tmp/salt/* /srv/salt

eselect profile set default/linux/amd64/17.1/desktop

rc-service salt-minion start
salt-call state.highstate --log-level info
