#!/bin/bash -uex

# Salt keywords are managed here as well as in salt/init.sls.
# It is probably best to keep them in sync.
mkdir --parents /etc/portage/package.accept_keywords/app-admin
echo '<app-admin/salt-2018.3.0' >> /etc/portage/package.accept_keywords/app-admin/salt

emerge --verbose --quiet app-admin/salt
rc-update add salt-minion

UID_GID=1337
groupadd -g $UID_GID evan
useradd -m -u $UID_GID -g $UID_GID -G audio,users,video,wheel -s /bin/bash evan
echo evan:secret | chpasswd

cp /tmp/minion /etc/salt/minion
echo $MINION_ID > /etc/salt/minion_id

OLD_UMASK=$(umask)
umask 077
mkdir --parents /etc/salt/gpgkeys
gpg --homedir /etc/salt/gpgkeys --import /tmp/pillar.asc
umask "${OLD_UMASK}"

mkdir --parents /srv/salt /srv/pillar
cp -r /tmp/pillar/* /srv/pillar
cp -r /tmp/salt/* /srv/salt
cat > /srv/salt/top.sls <<'EOF'
base:
  '*':
    - dotfiles
EOF

rc-service salt-minion start
salt-call state.highstate --log-level info
