#!/bin/bash

# Apply salt states

set -o errexit -o nounset

force=
dry_run=

help=$(cat <<'USAGE'
Usage: salt/salt-apply [OPTION]

  -f, --force    Replace salt states if they already exist
  -n, --dry-run  Use the test mode when applying salt states to avoid changes
  -h, --help     Display this help and exit
USAGE
)

opts="$(getopt -o fnh -l force,dry-run,help -n salt/salt-apply -- "$@")"
eval set -- "$opts"
while true; do case "$1" in
   -f|--force) shift; force='--force' ;;
   -n|--dry-run) shift; dry_run='test=True' ;;
   -h|--help) shift; echo "$help"; exit 0 ;;
   --) shift; break ;;
esac done

# Install salt if needed
if ! command -v salt-call > /dev/null 2>&1; then
   # Salt USE flags are managed here as well as in salt/init.sls.
   # It is probably best to keep them in sync.
   mkdir --parents /etc/portage/package.use/app-admin
   echo 'app-admin/salt gnupg portage vim-syntax' > /etc/portage/package.use/app-admin/salt
   # pyzmq seems to need zeromq drafts enabled?
   # https://bugs.gentoo.org/703252
   # https://bugs.gentoo.org/648088
   mkdir --parents /etc/portage/package.use/net-libs
   echo 'net-libs/zeromq drafts' > /etc/portage/package.use/net-libs/zeromq

   emerge --quiet app-admin/salt

   cp "${SOURCE:-salt}/salt.conf" /etc/salt/minion
   echo $MINION_ID > /etc/salt/minion_id
fi

# Replace salt states
if salt/salt-top "$force"; then :
else
   # Continue when --force is not used
   [ $? -ne 128 ] && exit 1
fi

# Generate pillar if needed
salt/salt-pillar

salt-call state.apply --log-level info "$dry_run"
