#!/bin/bash

# Prepare the salt state tree

set -o errexit -o nounset

# Use extended pattern matching to exclude .saltignore from copy in statedir
shopt -s extglob

SALT_DIR="${SALT_DIR:-/srv/salt}"
DOTFILES="${SALT_DIR}/dotfiles"

force=false

opts="$(getopt -o f -l force -n salt/salt-top -- "$@")"
eval set -- "$opts"
while true; do case "$1" in
   -f|--force) shift; force=true ;;
   --) shift; break ;;
esac done

if [ -d "$SALT_DIR" ] && ! $force; then
   (>&2 echo 'Refusing to replace salt states without --force')
   exit 128
fi

rm -rf "$SALT_DIR"
mkdir --parents "${DOTFILES}"

echo "dotfiles"
echo "include:" > "${DOTFILES}/init.sls"

add_to_init() {
   echo "  $1"
   echo "  - .$1" >> "${DOTFILES}/init.sls"
}

# Copies the entire state directory ignoring files listed in .saltignore
statedir() {
   local state=$1
   if [ -f "${state}/.saltignore" ]; then
      GLOBIGNORE=$(tr '\n' ':' < <(sed "s/.*/${state}\/&/" < "${state}/.saltignore"))
   else
      # Set a non-null value to implicitly enable dotglob to match all files,
      # including dot files.
      GLOBIGNORE=.
   fi
   cp --parents --recursive "$state"/!([.]saltignore) "${DOTFILES}"
   unset GLOBIGNORE

   # Assume files named after the state directory are init files
   local init_sls="${DOTFILES}/${state}/init.sls"
   local statedir_sls="${DOTFILES}/${state}/${state}.sls"
   if [ ! -f "$init_sls" ] && ! mv "$statedir_sls" "$init_sls"; then
      (>&2 echo "The '${state}' directory needs an init.sls or ${state}.sls state file")
      exit 1
   fi

   add_to_init "$state"
}

# Copies an individual salt state file
statefile() {
   local state=$1
   cp --parents "${state/\./\/}.sls" "${DOTFILES}"
   add_to_init "$state"
}

statedir portage
statedir awesome
statedir bash
statedir deluge
statedir firefox
statedir git
statedir gpg
statedir htop
statedir java
statedir minecraft
statedir pass
statedir salt
statedir smartcard
statedir ssh
statefile 'system.fonts'
statefile 'system.system'
statefile 'system.time'
statedir thunderbird
statedir tmux
statedir urxvt
statedir vim
statedir x11

cat > "${SALT_DIR}/top.sls" <<'EOF'
base:
  '*':
    - dotfiles
EOF
